{
    'name': 'Smart Out-of-Stock Badge for eCommerce',
    'version': '17.0.1.0.0',
    'summary': 'Automatic out-of-stock badge on product images when qty = 0',
    'category': 'Website/Website',
    'author': 'AKREM.KHELIFI',
    'website': 'https://github.com/Akremjs/Auto-Out-of-Stock-Ribbon-for-eCommerce',
    'license': 'LGPL-3',
    'depends': ['website_sale'],
    'data': ['views/badge.xml'],
    'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install': False,
    'application': False,
    'price': 0,
    'currency': 'EUR',
}